#!/bin/bash
# Bootstrap

# Concatenate the packages
SAVE_IFS=$IFS
IFS=","
include="${packages[*]}"
exclude="${exclude_packages[*]}"
IFS=$SAVE_IFS

# For bootstrapping purposes, we just use the first-listed mirror even if
# multiple are specified.
if [ -z "$bootstrap_mirror" ]; then
	bootstrap_mirror=${apt_mirrors%% *}
fi

bootstrap_args="--arch $arch --include=$include --exclude=$exclude
$codename $imagedir $bootstrap_mirror"

args_hash=`printf -- "$arch $include -- $exclude $codename" | sha1sum`

include_param=""
if [[ $include != "" ]]; then
	include_param="--include=$include"
fi

exclude_param=""
if [[ $exclude != "" ]]; then
	exclude_param="--exclude=$exclude"
fi

log "Bootstrapping"
debootstrap --arch $arch \
	${include_param} ${exclude_param} \
	$codename $imagedir $bootstrap_mirror | spin
[ $PIPESTATUS == 0 ] || die "Bootstrapping failed!"
