#!/bin/bash
# Mount special devices

unmount_specials() {
	if [ -n "$imagedir" ]; then
		cd $originaldir
		chroot $imagedir umount /dev/pts
		chroot $imagedir umount /sys
		chroot $imagedir umount /proc
		umount $imagedir/dev
	fi
}

cleanups+=("unmount_specials")

# Mount all the different special devices, other installers depend on their existence
mount --bind /dev $imagedir/dev
chroot $imagedir mount -t proc none /proc
chroot $imagedir mount -t sysfs none /sys
chroot $imagedir mount -t devpts none /dev/pts
