#!/bin/bash
# Unmount special devices

# We unmount from inside the image, otherwise the system won't boot
chroot $imagedir umount /dev/pts
chroot $imagedir umount /sys
chroot $imagedir umount /proc
umount $imagedir/dev

